sensor:
  - platform: template
    sensors:
      motion_sensor_attic_battery:
        friendly_name: "Attic Multisensor Battery"
        value_template: "{% if states.zwave.motion_sensor_attic %}
            {{ states.zwave.motion_sensor_attic.attributes.battery_level }}
          {% else %}
            unknown
          {% endif %}"
        unit_of_measurement: '%'
        # entity_id: zwave.motion_sensor_attic
        icon_template: >-
          {% set battery_level = states('sensor.motion_sensor_attic_battery')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
        entity_id: sensor.time

binary_sensor:
  - platform: template
    sensors:
      motion_sensor_attic_motion:
        value_template: "{{ is_state('sensor.motion_sensor_attic_burglar', '8') }}"
        friendly_name: "Attic Multisensor Motion"
        device_class: motion
        entity_id:  sensor.motion_sensor_attic_burglar

      motion_sensor_attic_tamper:
        value_template: "{{ is_state('sensor.motion_sensor_attic_burglar', '3') }}"
        friendly_name: "Attic Multisensor Tamper"
        device_class: safety
        entity_id:  sensor.motion_sensor_attic_burglar
      
group:
  motion_sensor_attic:
    name: Attic MultiSensor
    control: hidden
    entities:
      - binary_sensor.motion_sensor_attic_motion
      - binary_sensor.motion_sensor_attic_tamper
      - sensor.motion_sensor_attic_luminance
      - sensor.motion_sensor_attic_relative_humidity
      - sensor.motion_sensor_attic_temperature
      - sensor.motion_sensor_attic_battery