#sensor:
#  - platform: template
#    sensors:
#      motion_sensor_outdoor_battery:
#        friendly_name: "Outdoor Multisensor Battery"
#        value_template: "{% if states.zwave.motion_sensor_outdoor %}
#            {{ states.zwave.motion_sensor_outdoor.attributes.battery_level }}
#          {% else %}
#            unknown
#          {% endif %}"
#        unit_of_measurement: '%'
#        # entity_id: zwave.motion_sensor_outdoor
#        icon_template: >-
#          {% set battery_level = states('sensor.motion_sensor_outdoor_battery')|int('unknown') %}
#          {% set battery_round = (battery_level|int / 10)|int * 10 %}
#          {% if battery_level == 'unknown' %}
#            mdi:battery-unknown
#          {% else %}
#            {% if battery_round >= 100 %}
#              mdi:battery
#            {% elif battery_round > 0 %}
#              mdi:battery-{{ battery_round }}
#            {% else %}
#              mdi:battery-alert
#            {% endif %}
#          {% endif %}
#        entity_id: sensor.time

binary_sensor:
  - platform: template
    sensors:
      motion_sensor_outdoor_motion:
        value_template: "{{ is_state('sensor.motion_sensor_outdoor_burglar', '8') }}"
        friendly_name: "Motion Sensor (Outdoor)"
        device_class: motion
        entity_id:  sensor.motion_sensor_outdoor_burglar

      motion_sensor_outdoor_tamper:
        value_template: "{{ is_state('sensor.motion_sensor_outdoor_burglar', '3') }}"
        friendly_name: "Outdoor Multisensor Tamper"
        device_class: safety
        entity_id:  sensor.motion_sensor_outdoor_burglar
      
